# Generated by Django 4.1.4 on 2023-12-23 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25)),
                ('carModel', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('dateCreated', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=11, max_length=11, prefix='', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.TextField(default='None')),
                ('servicesPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('extraCost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cashOnDelivery', models.BooleanField(default=False)),
                ('payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('serviceType', models.CharField(choices=[('all', 'all'), ('grdn', 'grdn'), ('cwsh', 'cwsh'), ('hskp', 'hskp'), ('vhmn', 'vhmn'), ('vppi', 'vppi')], default='all', max_length=4)),
                ('onetime', models.BooleanField(default=False)),
                ('subscription', models.BooleanField(default=False)),
                ('percentageDiscount', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('maxDiscount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('uses', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=30)),
                ('package', models.CharField(choices=[('one-time', 'one-time'), ('subscription', 'subscription')], default='one-time', max_length=25)),
                ('startDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('endDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('numOfDays', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paused', models.BooleanField(default=False)),
                ('autoRenew', models.BooleanField(default=True)),
                ('description', models.TextField(default='None')),
                ('cartRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.cart')),
                ('checkoutRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.checkout')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=4)),
                ('numOfWorkers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHouseKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('maids', models.IntegerField()),
                ('supplies', models.BooleanField(default=False)),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.TextField(default='None')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicExteriorWash', models.IntegerField(blank=True, default=0, null=True)),
                ('interiorCleaning', models.IntegerField(blank=True, default=0, null=True)),
                ('BasicExteriorWithinteriorCleaning', models.IntegerField(blank=True, default=0, null=True)),
                ('exteriorWashWithWax', models.IntegerField(blank=True, default=0, null=True)),
                ('superDirtyExteriorWash', models.IntegerField(blank=True, default=0, null=True)),
                ('engineDetailing', models.IntegerField(blank=True, default=0, null=True)),
                ('basicExteriorWashSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('interiorCleaningSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('BasicExteriorWithinteriorCleaningSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('exteriorWashWithWaxSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('superDirtyExteriorWashSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('engineDetailingSUV', models.IntegerField(blank=True, default=0, null=True)),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.BooleanField(default=False)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.coupon'),
        ),
    ]
